class OurCustomGroupException(Exception):
    """Placeholder for ExceptionGroups introduced in Python 3.11"""

    pass
